/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Member;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import koneksi.New_ConnectDB;

/**
 *
 * @author server
 */
public class Daftar_Member extends javax.swing.JFrame {
     private Connection conn = new New_ConnectDB().connect();

    /**
     * Creates new form Daftar_Member
     */
    public Daftar_Member() {
        initComponents();
        setTanggal();
        tf_ttl.setForeground(Color.gray);
        setLocationRelativeTo(this);
    }
    
    
    public void setTanggal(){
    java.util.Date skrg = new java.util.Date();
    java.text.SimpleDateFormat kal = new
    java.text.SimpleDateFormat("dd/MM/yyyy");
    tnggl.setText(kal.format(skrg));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        tf_nis = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_nama = new javax.swing.JTextField();
        tf_kelas = new javax.swing.JTextField();
        tf_ttl = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cb_jeniskel = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        tf_email = new javax.swing.JTextField();
        tf_pass = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tf_pass2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        backgroud = new javax.swing.JLabel();
        tnggl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 35)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PENDAFTARAAN AKUN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, -1, -1));

        tf_nis.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 14)); // NOI18N
        tf_nis.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_nis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        tf_nis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nisActionPerformed(evt);
            }
        });
        getContentPane().add(tf_nis, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, 330, 30));

        jLabel8.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 18)); // NOI18N
        jLabel8.setText("NIS ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 70, 30));

        jLabel3.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 18)); // NOI18N
        jLabel3.setText("Nama");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 70, 30));

        jLabel7.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 18)); // NOI18N
        jLabel7.setText("Kelas");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 70, 30));

        tf_nama.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 14)); // NOI18N
        tf_nama.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_nama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        tf_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_namaActionPerformed(evt);
            }
        });
        getContentPane().add(tf_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 330, 30));

        tf_kelas.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 14)); // NOI18N
        tf_kelas.setForeground(new java.awt.Color(153, 153, 153));
        tf_kelas.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_kelas.setText("KELAS_JURUSAN?");
        tf_kelas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        tf_kelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_kelasMouseClicked(evt);
            }
        });
        tf_kelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_kelasActionPerformed(evt);
            }
        });
        getContentPane().add(tf_kelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 290, 330, 30));

        tf_ttl.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 14)); // NOI18N
        tf_ttl.setForeground(new java.awt.Color(153, 153, 153));
        tf_ttl.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_ttl.setText("Tanggal/Bulan/Tahun");
        tf_ttl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        tf_ttl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_ttlMouseClicked(evt);
            }
        });
        tf_ttl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_ttlActionPerformed(evt);
            }
        });
        tf_ttl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_ttlKeyPressed(evt);
            }
        });
        getContentPane().add(tf_ttl, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 330, 30));

        jLabel6.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 18)); // NOI18N
        jLabel6.setText("Tanggal Lahir");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, -1, 30));

        jLabel5.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 18)); // NOI18N
        jLabel5.setText("Jenis Kelamin");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, -1, 30));

        cb_jeniskel.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 14)); // NOI18N
        cb_jeniskel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan" }));
        cb_jeniskel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        getContentPane().add(cb_jeniskel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, 120, 30));

        jLabel10.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 18)); // NOI18N
        jLabel10.setText("Email");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 130, 30));

        tf_email.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 14)); // NOI18N
        tf_email.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        tf_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_emailActionPerformed(evt);
            }
        });
        getContentPane().add(tf_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 410, 330, 30));

        tf_pass.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 14)); // NOI18N
        tf_pass.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_pass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        tf_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_passActionPerformed(evt);
            }
        });
        getContentPane().add(tf_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, 330, 30));

        jLabel12.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 18)); // NOI18N
        jLabel12.setText("Masukan Sandi");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 450, -1, 30));

        jLabel11.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 18)); // NOI18N
        jLabel11.setText("Ulangi Sandi");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 490, 130, 30));

        tf_pass2.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 14)); // NOI18N
        tf_pass2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tf_pass2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        tf_pass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_pass2ActionPerformed(evt);
            }
        });
        tf_pass2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_pass2KeyReleased(evt);
            }
        });
        getContentPane().add(tf_pass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 490, 330, 30));

        jPanel2.setBackground(new java.awt.Color(0, 255, 0));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("SIMPAN");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 560, 130, 40));

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("KEMBALI");
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 560, 110, 40));

        jLabel4.setFont(new java.awt.Font("Arial Black", 3, 22)); // NOI18N
        jLabel4.setText("PERPUSTAKAAN");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 230, 20));

        backgroud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pendaptaran member.png"))); // NOI18N
        getContentPane().add(backgroud, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 680));

        tnggl.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 15)); // NOI18N
        tnggl.setText("Tanggal Pendaftaraan ");
        getContentPane().add(tnggl, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 220, 170, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_nisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nisActionPerformed

    private void tf_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_namaActionPerformed

    private void tf_kelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_kelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_kelasActionPerformed

    private void tf_ttlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_ttlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_ttlActionPerformed

    private void tf_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_emailActionPerformed

    private void tf_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_passActionPerformed

    private void tf_pass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_pass2ActionPerformed
        // TODO add your handling code here:
        int a = Integer.parseInt(tf_pass.getText());
        int b = Integer.parseInt(tf_pass2.getText());
        if (b != a) {
            //JOptionPane.showMessageDialog(null, "Akun Berhasil di Buat");
        } else{
            JOptionPane.showMessageDialog(null, "Password tidak sesuai");
        }
        
    }//GEN-LAST:event_tf_pass2ActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        new LoginSiswa().setVisible(true);
        String sql = "insert into member(nis,nama,kelas,tanggal_lahir,jenis_kelamin,email,password)values (?,?,?,?,?,?,?);";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, tf_nis.getText());
            stat.setString(2, tf_nama.getText());
            stat.setString(3, tf_kelas.getText());
            stat.setString(4, tf_ttl.getText());
            stat.setString(5, (String) cb_jeniskel.getSelectedItem());
            stat.setString(6, tf_email.getText());
            stat.setString(7, tf_pass.getText());
            //int a = Integer.parseInt(tf_KWH.getText());
            //int b = Integer.parseInt(tf_used.getText());
            //int kwh = 1467;
            //int stotal;
            //stotal = b * kwh;
            //String fix = Integer.toString(stotal);
            //stat.setString(5, fix);
            stat.executeUpdate();
            //update_kwh();
            JOptionPane.showMessageDialog(null, "Akun Berhasil di Buat");
            //kosong_payment();
            //new FormLoginUtama().setVisible(true);
            //tfregist_user.requestFocus();
            //dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Akun Gagal di Buat " + e);
        }
    }//GEN-LAST:event_jPanel2MouseClicked

    private void tf_pass2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_pass2KeyReleased
        // TODO add your handling code here:
        if (tf_pass.getText()!=tf_pass2.getText()) {
            //JOptionPane.showMessageDialog(null, "Akun Berhasil di Buat");
        } else{
            JOptionPane.showMessageDialog(null, "Password tidak sesuai");
        }
    }//GEN-LAST:event_tf_pass2KeyReleased

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        if(tf_nis.getText().equals("")){
                JOptionPane.showMessageDialog(null,"NIS Tidak Boleh Kosong / NIS Kurang Lengkap"); 
            }else if (tf_nama.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Nama Tidak Boleh Kosong"); 
            }else if (tf_kelas.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Kolom Tidak Boleh Kosong, Mohon di isi dengan Benar");
            }else if (tf_ttl.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Kolom Tidak Boleh Kososng / Harap Isi Kolom Dengan Benar");
            }else if(tf_email.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Email Tidak Boleh Kosong / Mohon di Isi dengan Tepat");
            } else if (tf_pass.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Password Tidak Boleh Kosong");
            } else if (tf_pass2.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Password Tidak Boleh Kosong");
            }else {

        
        
         new LoginSiswa().setVisible(true);
        String sql = "insert into member (nis,nama,kelas,tanggal_lahir,jenis_kelamin,email,password,tanggal_login)values (?,?,?,?,?,?,?,?);";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, tf_nis.getText());
            stat.setString(2, tf_nama.getText());
            stat.setString(3, tf_kelas.getText());
            stat.setString(4, tf_ttl.getText());
            stat.setString(5, (String) cb_jeniskel.getSelectedItem());
            stat.setString(6, tf_email.getText());
            stat.setString(7, tf_pass.getText());
            stat.setString(8, tnggl.getText());
            stat.executeUpdate();
            //update_kwh();
            JOptionPane.showMessageDialog(null, "Akun Berhasil di Buat");
            dispose();
            //kosong_payment();
            //dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Akun Gagal di Buat " + e);
        }
            }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        dispose();
        new LoginSiswa().setVisible(true);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void tf_ttlKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_ttlKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_ttlKeyPressed

    private void tf_ttlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_ttlMouseClicked
        // TODO add your handling code here:
        tf_ttl.setText("");
        tf_ttl.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_tf_ttlMouseClicked

    private void tf_kelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_kelasMouseClicked
        // TODO add your handling code here:
        tf_kelas.setText("");
        tf_kelas.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_tf_kelasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Daftar_Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Daftar_Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Daftar_Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Daftar_Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Daftar_Member().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroud;
    private javax.swing.JComboBox<String> cb_jeniskel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_kelas;
    private javax.swing.JTextField tf_nama;
    private javax.swing.JTextField tf_nis;
    private javax.swing.JTextField tf_pass;
    private javax.swing.JTextField tf_pass2;
    private javax.swing.JTextField tf_ttl;
    private javax.swing.JLabel tnggl;
    // End of variables declaration//GEN-END:variables
}
