/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Member;

import com.Admin.*;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import koneksi.New_ConnectDB;

/**
 *
 * @author server
 */
public class LoginSiswa extends javax.swing.JFrame {
    private New_ConnectDB conn = new New_ConnectDB();

    /**
     * Creates new form Login
     */
    public LoginSiswa() {
        initComponents();
        setLocationRelativeTo(this);
        setTanggal();
         jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
         
    }
    
    
     protected void kosong() {
        tf_NIS.setText("");
        PWMEMBER.setText("");
    }
     
      public void setTanggal(){
    java.util.Date skrg = new java.util.Date();
    java.text.SimpleDateFormat kal = new
    java.text.SimpleDateFormat("dd/MM/yyyy");
    jltanggal.setText(kal.format(skrg));
    }
     
      protected void History_Login() {
           String sql = "insert into history_login (tanggal_terakhir_login,nis,nama)values (?,?,?);";
        try {
            PreparedStatement stat = conn.connect().prepareStatement(sql);
            stat.setString(1, jltanggal.getText());
            stat.setString(2,tf_NIS.getText());
            stat.setString(3, tumbal_nama.getText());
            stat.executeUpdate();
            
            //update_kwh();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Akun Gagal di Buat " + e);
        }
    }
      
      protected void Nama() {
        try {
            String sql = "select * from member where nis = '" + tf_NIS.getText() + "'";
            Statement stat = conn.connect().createStatement();
            ResultSet rsLogin = stat.executeQuery(sql);
 
            rsLogin.next();
            rsLogin.last(); //mengecek jumlah baris pada hasil query
            if (rsLogin.getRow()==1){
                String snama = rsLogin.getString("nama");
                
                tumbal_nama.setText(""+snama);
            } else {
                
            }
        } catch (SQLException e) {
        }

      }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_NIS = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        PWMEMBER = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        tumbal_nama = new javax.swing.JLabel();
        jltanggal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 3, 22)); // NOI18N
        jLabel1.setText("PERPUSTAKAAN ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 230, 20));

        jPanel2.setBackground(new java.awt.Color(0, 255, 0));
        jPanel2.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel2AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Open Sans ExtraBold", 3, 20)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Masuk");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 555, 190, 50));

        jLabel2.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 50)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LOGIN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, -1, 50));

        jLabel5.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 20)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Selamat Datang di Perpustakaan Kami!");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, -1, 30));

        jLabel6.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 15)); // NOI18N
        jLabel6.setText("MASUKAN NIS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 140, 20));

        tf_NIS.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 12)); // NOI18N
        tf_NIS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        tf_NIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_NISActionPerformed(evt);
            }
        });
        tf_NIS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_NISKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_NISKeyReleased(evt);
            }
        });
        getContentPane().add(tf_NIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 300, 30));

        jLabel3.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 15)); // NOI18N
        jLabel3.setText("MASUKAN SANDI");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 150, 20));

        PWMEMBER.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 12)); // NOI18N
        PWMEMBER.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        PWMEMBER.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PWMEMBERMouseClicked(evt);
            }
        });
        PWMEMBER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PWMEMBERActionPerformed(evt);
            }
        });
        PWMEMBER.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                PWMEMBERKeyPressed(evt);
            }
        });
        getContentPane().add(PWMEMBER, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, 300, 30));

        jLabel10.setFont(new java.awt.Font("Open Sans ExtraBold", 3, 20)); // NOI18N
        jLabel10.setText("Lupa Sandi ?");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 455, -1, -1));

        jLabel12.setFont(new java.awt.Font("Open Sans ExtraBold", 3, 20)); // NOI18N
        jLabel12.setText("Buat Akun");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 490, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arrow left.png"))); // NOI18N
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 60, 50));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/login member.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 680));

        tumbal_nama.setText("jLabel4");
        getContentPane().add(tumbal_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 360, -1, -1));

        jltanggal.setText("jLabel4");
        getContentPane().add(jltanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel2AncestorAdded
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jPanel2AncestorAdded

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jPanel2MouseClicked

    private void tf_NISKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_NISKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER){
            PWMEMBER.requestFocus();
        }
    }//GEN-LAST:event_tf_NISKeyPressed

    private void PWMEMBERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PWMEMBERActionPerformed
        // TODO add your handling code here:
       conn.connect();
        try {
            String sql = "select * from member where nis = '" + tf_NIS.getText() + "' and Password = '" + PWMEMBER.getText() + "'";
            Statement stat = conn.connect().createStatement();
            ResultSet rsLogin = stat.executeQuery(sql);
 
            rsLogin.next();
            rsLogin.last(); //mengecek jumlah baris pada hasil query
            if (rsLogin.getRow()==1){
                JOptionPane.showMessageDialog(null, "Login Berhasil!");
                History_Login();
                dispose();
                
                String snama = rsLogin.getString("nama");
                String nis = rsLogin.getString("nis");
                String tanggal_lahir = rsLogin.getString("tanggal_lahir");
                String email = rsLogin.getString("email");
                String jenis_kelamin = rsLogin.getString("jenis_kelamin");
                String kelas = rsLogin.getString("kelas");
                String password = rsLogin.getString("password");
                
                Home_Member b= new Home_Member();
                b.jLabel7.setText(""+snama);
                b.Tumbal_nohp.setText(""+nis);
                b.Tumbal_email.setText(""+email);
                b.Tumbal_kelas.setText(""+kelas);
                b.Tumbal_TTL.setText(""+tanggal_lahir);
                b.Tumbal_jenisKel.setText(""+jenis_kelamin);
                b.tumbal_nis.setText(""+nis);
                b.PS_TB_HOME.setText(password);
                b.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Maaf, No Handphone / Password anda salah!");
                kosong();
                tf_NIS.requestFocus();
            }
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_PWMEMBERActionPerformed

    private void PWMEMBERKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PWMEMBERKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_PWMEMBERKeyPressed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        dispose();
        new LupaPassword_Member().setVisible(true);
        
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        dispose();
        new Daftar_Member().setVisible(true);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
       conn.connect();
        try {
            String sql = "select * from member where nis = '" + tf_NIS.getText() + "' and Password = '" + PWMEMBER.getText() + "'";
            Statement stat = conn.connect().createStatement();
            ResultSet rsLogin = stat.executeQuery(sql);
 
            rsLogin.next();
            rsLogin.last(); //mengecek jumlah baris pada hasil query
            if (rsLogin.getRow()==1){
                JOptionPane.showMessageDialog(null, "Login Berhasil!");
                History_Login();
                dispose();
                
                String snama = rsLogin.getString("nama");
                String nis = rsLogin.getString("nis");
                String tanggal_lahir = rsLogin.getString("tanggal_lahir");
                String email = rsLogin.getString("email");
                String jenis_kelamin = rsLogin.getString("jenis_kelamin");
                String kelas = rsLogin.getString("kelas");
                String password = rsLogin.getString("password");
                
                Home_Member b= new Home_Member();
                b.jLabel7.setText(""+snama);
                b.Tumbal_nohp.setText(""+nis);
                b.Tumbal_email.setText(""+email);
                b.Tumbal_kelas.setText(""+kelas);
                b.Tumbal_TTL.setText(""+tanggal_lahir);
                b.Tumbal_jenisKel.setText(""+jenis_kelamin);
                b.tumbal_nis.setText(""+nis);
                b.PS_TB_HOME.setText(password);
                b.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(null, "Maaf, No Handphone / Password anda salah!");
                kosong();
                tf_NIS.requestFocus();
            }
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        dispose();
        new TampilanAwal().setVisible(true);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void tf_NISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_NISActionPerformed
        // TODO add your handling code here:
        Nama();
    }//GEN-LAST:event_tf_NISActionPerformed

    private void tf_NISKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_NISKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_NISKeyReleased

    private void PWMEMBERMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PWMEMBERMouseClicked
        // TODO add your handling code here:
        try {
            String sql = "select * from member where nis = '" + tf_NIS.getText() + "'";
            Statement stat = conn.connect().createStatement();
            ResultSet rsLogin = stat.executeQuery(sql);
 
            rsLogin.next();
            rsLogin.last(); //mengecek jumlah baris pada hasil query
            if (rsLogin.getRow()==1){
                String snama = rsLogin.getString("nama");
                
                tumbal_nama.setText(""+snama);
            } else {
                
            }
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_PWMEMBERMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginSiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PWMEMBER;
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jltanggal;
    private javax.swing.JTextField tf_NIS;
    public static javax.swing.JLabel tumbal_nama;
    // End of variables declaration//GEN-END:variables
}
