/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Member;

import com.Admin.*;

/**
 *
 * @author Hard JFS
 */
public class popuptrending4 extends javax.swing.JFrame {

    /**
     * Creates new form popuptrending4
     */
    public popuptrending4() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        vir_stokMember4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        vir_judulMember4 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        vir_penulisMember4 = new javax.swing.JLabel();
        vir_penerbitMember4 = new javax.swing.JLabel();
        vir_tahunMember4 = new javax.swing.JLabel();
        vir_isbnMember4 = new javax.swing.JLabel();
        Penulis4 = new javax.swing.JLabel();
        Penerbit4 = new javax.swing.JLabel();
        Tahun_Terbit4 = new javax.swing.JLabel();
        Isbn4 = new javax.swing.JLabel();
        bgpopup = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/open-book(3).png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 45, 80, 60));

        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 50));

        vir_stokMember4.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 14)); // NOI18N
        vir_stokMember4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vir_stokMember4.setText("00000");
        getContentPane().add(vir_stokMember4, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 172, -1, 30));

        jLabel6.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 14)); // NOI18N
        jLabel6.setText("Stok Buku");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 172, -1, 30));

        jLabel3.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 14)); // NOI18N
        jLabel3.setText("Rating");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 143, -1, 20));

        vir_judulMember4.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 18)); // NOI18N
        vir_judulMember4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vir_judulMember4.setText("Judul Buku");
        getContentPane().add(vir_judulMember4, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 110, 323, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bintang 4.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 140, 130, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arrow left.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 50));

        vir_penulisMember4.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 18)); // NOI18N
        vir_penulisMember4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        vir_penulisMember4.setText("?");
        getContentPane().add(vir_penulisMember4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 295, 30));

        vir_penerbitMember4.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 18)); // NOI18N
        vir_penerbitMember4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        vir_penerbitMember4.setText("?");
        getContentPane().add(vir_penerbitMember4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 295, 30));

        vir_tahunMember4.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 18)); // NOI18N
        vir_tahunMember4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        vir_tahunMember4.setText("?");
        getContentPane().add(vir_tahunMember4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 295, 30));

        vir_isbnMember4.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 18)); // NOI18N
        vir_isbnMember4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        vir_isbnMember4.setText("?");
        getContentPane().add(vir_isbnMember4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 295, 30));

        Penulis4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Penulis4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Penulis4.setText("Penulis :");
        getContentPane().add(Penulis4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 225, -1, -1));

        Penerbit4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Penerbit4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Penerbit4.setText("Penerbit :");
        getContentPane().add(Penerbit4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        Tahun_Terbit4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Tahun_Terbit4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tahun_Terbit4.setText("Tahun Terbit :");
        getContentPane().add(Tahun_Terbit4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        Isbn4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Isbn4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Isbn4.setText("ISBN :");
        getContentPane().add(Isbn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        bgpopup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pop up tr1.png"))); // NOI18N
        bgpopup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bgpopupMouseExited(evt);
            }
        });
        getContentPane().add(bgpopup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        dispose();
        new Home_Admin().setVisible(true);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void bgpopupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgpopupMouseExited
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_bgpopupMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(popuptrending4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(popuptrending4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(popuptrending4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(popuptrending4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new popuptrending4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Isbn4;
    private javax.swing.JLabel Penerbit4;
    private javax.swing.JLabel Penulis4;
    private javax.swing.JLabel Tahun_Terbit4;
    private javax.swing.JLabel bgpopup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JLabel vir_isbnMember4;
    public static javax.swing.JLabel vir_judulMember4;
    public static javax.swing.JLabel vir_penerbitMember4;
    public static javax.swing.JLabel vir_penulisMember4;
    public static javax.swing.JLabel vir_stokMember4;
    public static javax.swing.JLabel vir_tahunMember4;
    // End of variables declaration//GEN-END:variables
}
