/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Member;

import com.Admin.*;

/**
 *
 * @author Hard JFS
 */
public class Popuptrending2 extends javax.swing.JFrame {

    /**
     * Creates new form Popuptrending2
     */
    public Popuptrending2() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        vir_stokMember2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        vir_judulMember2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        vir_penulisMember2 = new javax.swing.JLabel();
        vir_penerbitMember2 = new javax.swing.JLabel();
        vir_tahunMember2 = new javax.swing.JLabel();
        vir_isbnMember2 = new javax.swing.JLabel();
        Penulis2 = new javax.swing.JLabel();
        Penerbit2 = new javax.swing.JLabel();
        Tahun_Terbit2 = new javax.swing.JLabel();
        Isbn2 = new javax.swing.JLabel();
        bgpopup = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 50));

        jLabel6.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 14)); // NOI18N
        jLabel6.setText("Stok Buku");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 172, -1, 30));

        vir_stokMember2.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 14)); // NOI18N
        vir_stokMember2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vir_stokMember2.setText("00000");
        getContentPane().add(vir_stokMember2, new org.netbeans.lib.awtextra.AbsoluteConstraints(227, 172, -1, 30));

        jLabel3.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 14)); // NOI18N
        jLabel3.setText("Rating");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 143, -1, 20));

        vir_judulMember2.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 18)); // NOI18N
        vir_judulMember2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vir_judulMember2.setText("Judul Buku");
        getContentPane().add(vir_judulMember2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 110, 323, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/study.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 45, 80, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bintang 2.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 140, 130, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arrow left.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 50));

        vir_penulisMember2.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 18)); // NOI18N
        vir_penulisMember2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        vir_penulisMember2.setText("?");
        getContentPane().add(vir_penulisMember2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 295, 30));

        vir_penerbitMember2.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 18)); // NOI18N
        vir_penerbitMember2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        vir_penerbitMember2.setText("?");
        getContentPane().add(vir_penerbitMember2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 295, 30));

        vir_tahunMember2.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 18)); // NOI18N
        vir_tahunMember2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        vir_tahunMember2.setText("?");
        getContentPane().add(vir_tahunMember2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 295, 30));

        vir_isbnMember2.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 18)); // NOI18N
        vir_isbnMember2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        vir_isbnMember2.setText("?");
        getContentPane().add(vir_isbnMember2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 295, 30));

        Penulis2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Penulis2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Penulis2.setText("Penulis :");
        getContentPane().add(Penulis2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 225, -1, -1));

        Penerbit2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Penerbit2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Penerbit2.setText("Penerbit :");
        getContentPane().add(Penerbit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        Tahun_Terbit2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Tahun_Terbit2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tahun_Terbit2.setText("Tahun Terbit :");
        getContentPane().add(Tahun_Terbit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        Isbn2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Isbn2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Isbn2.setText("ISBN :");
        getContentPane().add(Isbn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        bgpopup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pop up tr1.png"))); // NOI18N
        bgpopup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bgpopupMouseExited(evt);
            }
        });
        getContentPane().add(bgpopup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        dispose();
        new Home_Admin().setVisible(true);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void bgpopupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgpopupMouseExited
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_bgpopupMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Popuptrending2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Popuptrending2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Popuptrending2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Popuptrending2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Popuptrending2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Isbn2;
    private javax.swing.JLabel Penerbit2;
    private javax.swing.JLabel Penulis2;
    private javax.swing.JLabel Tahun_Terbit2;
    private javax.swing.JLabel bgpopup;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel vir_isbnMember2;
    public static javax.swing.JLabel vir_judulMember2;
    public static javax.swing.JLabel vir_penerbitMember2;
    public static javax.swing.JLabel vir_penulisMember2;
    public static javax.swing.JLabel vir_stokMember2;
    public static javax.swing.JLabel vir_tahunMember2;
    // End of variables declaration//GEN-END:variables
}
