/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Admin;

/**
 *
 * @author Hard JFS
 */
public class bukumerah extends javax.swing.JFrame {

    /**
     * Creates new form bukumerah
     */
    public bukumerah() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ala_judul2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ala_stok2 = new javax.swing.JLabel();
        ala_penulis2 = new javax.swing.JLabel();
        ala_penerbit2 = new javax.swing.JLabel();
        ala_tahun2 = new javax.swing.JLabel();
        ala_isbn2 = new javax.swing.JLabel();
        Penulis1a = new javax.swing.JLabel();
        Penerbit1a = new javax.swing.JLabel();
        Tahun_Terbit1a = new javax.swing.JLabel();
        Isbn1a = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arrow left.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 50));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/book 2.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 20, 80, 90));

        ala_judul2.setBackground(new java.awt.Color(255, 255, 255));
        ala_judul2.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 18)); // NOI18N
        ala_judul2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ala_judul2.setText("Judul Buku");
        getContentPane().add(ala_judul2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 110, 330, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bintang 1.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 140, 130, -1));

        jLabel3.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 14)); // NOI18N
        jLabel3.setText("Rating");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 143, -1, 20));

        jLabel9.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 14)); // NOI18N
        jLabel9.setText("Stok Buku ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 172, -1, 30));

        ala_stok2.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 14)); // NOI18N
        ala_stok2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ala_stok2.setText("00000");
        getContentPane().add(ala_stok2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 172, -1, 30));

        ala_penulis2.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 18)); // NOI18N
        ala_penulis2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ala_penulis2.setText("?");
        getContentPane().add(ala_penulis2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 300, 30));

        ala_penerbit2.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 18)); // NOI18N
        ala_penerbit2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ala_penerbit2.setText("?");
        getContentPane().add(ala_penerbit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 300, 30));

        ala_tahun2.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 18)); // NOI18N
        ala_tahun2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ala_tahun2.setText("?");
        getContentPane().add(ala_tahun2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 300, 30));

        ala_isbn2.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 18)); // NOI18N
        ala_isbn2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ala_isbn2.setText("?");
        getContentPane().add(ala_isbn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 300, 30));

        Penulis1a.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Penulis1a.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Penulis1a.setText("Penulis :");
        getContentPane().add(Penulis1a, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 225, -1, -1));

        Penerbit1a.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Penerbit1a.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Penerbit1a.setText("Penerbit :");
        getContentPane().add(Penerbit1a, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        Tahun_Terbit1a.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Tahun_Terbit1a.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tahun_Terbit1a.setText("Tahun Terbit :");
        getContentPane().add(Tahun_Terbit1a, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        Isbn1a.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Isbn1a.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Isbn1a.setText("ISBN :");
        getContentPane().add(Isbn1a, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/popuptrenAD.png"))); // NOI18N
        BG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BGMouseExited(evt);
            }
        });
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void BGMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BGMouseExited
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BGMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bukumerah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bukumerah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bukumerah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bukumerah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bukumerah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel Isbn1a;
    private javax.swing.JLabel Penerbit1a;
    private javax.swing.JLabel Penulis1a;
    private javax.swing.JLabel Tahun_Terbit1a;
    public static javax.swing.JLabel ala_isbn2;
    public static javax.swing.JLabel ala_judul2;
    public static javax.swing.JLabel ala_penerbit2;
    public static javax.swing.JLabel ala_penulis2;
    public static javax.swing.JLabel ala_stok2;
    public static javax.swing.JLabel ala_tahun2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
