/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Admin;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import koneksi.New_ConnectDB;

/**
 *
 * @author Hard JFS
 */
public class melihatprofileADMIN extends javax.swing.JFrame {
    private Connection conn = new New_ConnectDB().connect();

    /**
     * Creates new form melihatprofile
     */
    public melihatprofileADMIN() {
        initComponents();
        dataAdmin();
        setLocationRelativeTo(this);
    }
    
    
    protected void kosong(){
        UP_mail.setText("");
        pass.setText("");
        UP_SANDI2.setText("");
        UP_SANDI3.setText("");
    }
    
    
    protected void dataAdmin() {
         Object[]baris = {"no_handphone","nama","tanggal_lahir","email","jenis_kelamin"};
         String sql = "select * from admin where no_handphone ";//asc paling kecil
         
         try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String no_hp = hasil.getString("no_handphone");
                String nama = hasil.getString("nama");
                String tanggal_lahir = hasil.getString("tanggal_lahir");
                String email = hasil.getString("email");
                String jenis_kelamin = hasil.getString("jenis_kelamin");
                String[] data = {no_hp,nama, tanggal_lahir, email, jenis_kelamin};
                NoHP.setText(no_hp);
                Nama.setText(nama);
                TanggalLahir.setText(tanggal_lahir);
                Email.setText(email);
                JenisKelamin.setText(jenis_kelamin);
                //tabmode.addRow(data);

            }
        } catch (Exception e) {
        }
         
         

        
    }
    
    protected void UBAH() {
        String sql = "select email from admin where no_handphone  = '"+ NoHP.getText() + "' ";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String snis = hasil.getString("email");
                //String[] data = {no_hp,nama, tanggal_lahir, email, jenis_kelamin};
                Email.setText(snis);
                //tabmode.addRow(data);

            }
        } catch (Exception e) {
        }
    }
    
    
     protected void sandi() {
        String sql = "select password from admin where no_handphone  = '"+ PS_TB.getText() + "' ";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String sPASS = hasil.getString("password");
                PS_TB.setText(sPASS);
                //tabmode.addRow(data);

            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TanggalLahir = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        UP_SANDI3 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        UP_mail = new javax.swing.JTextField();
        pass = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Nama = new javax.swing.JLabel();
        NoHP = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        JenisKelamin = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        UP_SANDI2 = new javax.swing.JTextField();
        bgpopupaktivitas = new javax.swing.JLabel();
        PS_TB = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TanggalLahir.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 18)); // NOI18N
        TanggalLahir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TanggalLahir.setText("Tanggal Lahir");
        getContentPane().add(TanggalLahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 230, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/RecAKTIV1.png"))); // NOI18N
        jLabel3.setAlignmentY(25.0F);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 260, 40));

        Email.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 18)); // NOI18N
        Email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Email.setText("Email");
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 230, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/RecAKTIV1.png"))); // NOI18N
        jLabel4.setAlignmentY(25.0F);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 260, 40));

        jLabel12.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("SIMPAN");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 335, 140, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/RectAKTIV2.png"))); // NOI18N
        jLabel6.setAlignmentY(25.0F);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 170, 40));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arrow left.png"))); // NOI18N
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 50));

        UP_SANDI3.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 12)); // NOI18N
        UP_SANDI3.setEnabled(false);
        getContentPane().add(UP_SANDI3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 290, 30));

        jLabel17.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 14)); // NOI18N
        jLabel17.setText("Konfirmasi kata sandi:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 200, 20));

        UP_mail.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 12)); // NOI18N
        UP_mail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(UP_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 290, 30));

        pass.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 12)); // NOI18N
        pass.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passActionPerformed(evt);
            }
        });
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 290, 30));

        jLabel19.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 14)); // NOI18N
        jLabel19.setText("Ubah Email :");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, 120, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/profile-user 1 (1) 1.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 30, -1, -1));

        Nama.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 25)); // NOI18N
        Nama.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nama.setText("Nama Pengguna");
        getContentPane().add(Nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 95, 325, -1));

        NoHP.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 12)); // NOI18N
        NoHP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NoHP.setText("No handphone");
        getContentPane().add(NoHP, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 130, 150, -1));

        jLabel20.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 14)); // NOI18N
        jLabel20.setText("Masukkan kata sandi lama :");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 160, 240, 20));

        JenisKelamin.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 12)); // NOI18N
        JenisKelamin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JenisKelamin.setText("Jenis kelamin");
        getContentPane().add(JenisKelamin, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 10, 100, -1));

        jLabel21.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 14)); // NOI18N
        jLabel21.setText("Buat kata sandi baru:");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 200, 20));

        UP_SANDI2.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 12)); // NOI18N
        UP_SANDI2.setEnabled(false);
        getContentPane().add(UP_SANDI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 290, 30));

        bgpopupaktivitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mypropAD.png"))); // NOI18N
        getContentPane().add(bgpopupaktivitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        PS_TB.setText("jLabel1");
        getContentPane().add(PS_TB, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        if(UP_mail.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Column Tidak Boleh Kosong / Column Kurang Lengkap"); 
            }else if (pass.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Column Tidak Boleh Kosong"); 
            }else if (UP_SANDI2.getText().equals("")){
                 JOptionPane.showMessageDialog(null,"Column Tidak Boleh Kosong");
            }else if (UP_SANDI3.getText().equals("")){
                 JOptionPane.showMessageDialog(null,"Column Tidak Boleh Kosong");
            }else {
        
         try {
            String sql = "update admin set email=?, password=? where no_handphone ='" + NoHP.getText()+"'";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, UP_mail.getText());
            stat.setString(2, UP_SANDI2.getText());
            stat.executeUpdate();
            UBAH();
            JOptionPane.showMessageDialog(null,
                    "Data berhasil di ubah");
            kosong();
            
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null,
                    "Data gagal diubah" +e);
        }
            }
    }//GEN-LAST:event_jLabel12MouseClicked

    private void passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passActionPerformed
        // TODO add your handling code here:
        if(pass.getText().equals(""+PS_TB.getText())){
                UP_SANDI2.setEnabled(true);
                UP_SANDI3.setEnabled(true);
            }else {
                JOptionPane.showMessageDialog(null,"Password Tidak Sesuai"); 
                UP_SANDI2.setEnabled(false);
                UP_SANDI3.setEnabled(false);
            }
    }//GEN-LAST:event_passActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(melihatprofileADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(melihatprofileADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(melihatprofileADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(melihatprofileADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new melihatprofileADMIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel Email;
    public static javax.swing.JLabel JenisKelamin;
    public static javax.swing.JLabel Nama;
    public static javax.swing.JLabel NoHP;
    public static javax.swing.JLabel PS_TB;
    public static javax.swing.JLabel TanggalLahir;
    private javax.swing.JTextField UP_SANDI2;
    private javax.swing.JTextField UP_SANDI3;
    private javax.swing.JTextField UP_mail;
    private javax.swing.JLabel bgpopupaktivitas;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField pass;
    // End of variables declaration//GEN-END:variables
}
