/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Admin;

import static com.Admin.melihatprofileADMIN.Email;
import static com.Admin.melihatprofileADMIN.JenisKelamin;
import static com.Admin.melihatprofileADMIN.Nama;
import static com.Admin.melihatprofileADMIN.NoHP;
import static com.Admin.melihatprofileADMIN.TanggalLahir;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import koneksi.New_ConnectDB;

/**
 *
 * @author server
 */
public class Peminjaman1 extends javax.swing.JFrame {
    private Connection conn = new New_ConnectDB().connect();

    /**
     * Creates new form Peminjaman1
     */
    public Peminjaman1() {
        initComponents();
        setLocationRelativeTo(this);
        auto_number();
        
    }
    
    
     protected void nama() {
         String sql = "select nama from member where nis = '"+ tf_NIS.getText() + "' ";//asc paling kecil
         
         try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String sjudul = hasil.getString("nama");
                tf_nama.setText(sjudul);
                //tabmode.addRow(data);

            }
        } catch (Exception e) {
        }
     }
    
     protected void dataAdmin() {
         String sql = "select * from data_buku where ISBN = '"+ tf_ISBN.getText() + "' ";//asc paling kecil
         
         try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String sjudul = hasil.getString("judul");
                tf_judul.setText(sjudul);
                //tabmode.addRow(data);

            }
        } catch (Exception e) {
        }
         
    }
    
     
     
     protected void stok() {
         String sql = "select * from data_buku where ISBN = '"+ tf_ISBN.getText() + "' ";//asc paling kecil
         
         try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String sjudul = hasil.getString("jumlah");
                tumbal_stok.setText(sjudul);
                //tabmode.addRow(data);

            }
        } catch (Exception e) {
        }
         
    }
    protected void Update_Stok() {
        int a = Integer.parseInt(tumbal_stok.getText());
        int stotal = a - 1;
        tumbal_update_stok.setText(""+stotal);
        try {
            String sql = "update data_buku set jumlah='"+tumbal_update_stok.getText()+"' where ISBN='"+tf_ISBN.getText()+"'";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.executeUpdate();
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null,
                    "Hubungi Administrator +62 8778-8298-067" +e);
        }
    }
    
    protected void kosong(){
        tf_NIS.setText("");
        tf_nama.setText("");
        tf_ISBN.setText("");
        tf_judul.setText("");
        tf_tanggalpin.setText("");
        tf_tanggalkem.setText("");
        tf_nohp.setText("");
    }
    
    
    protected void auto_number(){
        try {
            String sql="select * from peminjaman order by kodepinjam desc";
            java.sql.Statement stat=conn.createStatement();
            ResultSet hasil=stat.executeQuery(sql);
            if (hasil.next()) {
                String auto = hasil.getString("kodepinjam").substring(1);
                String AN = "" + (Integer.parseInt(auto) + 1);
                String Nol = "";

                if(AN.length()==1)
                {Nol = "000";}
                else if(AN.length()==2)
                {Nol = "00";}
                else if(AN.length()==3)
                {Nol = "0";}
                else if(AN.length()==4)
                {Nol = "";}
                
               tf_kodepinjam1.setText("P" + Nol + AN);
            } else {
               tf_kodepinjam1.setText("P0001");
            }

           }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
           }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf_NIS = new javax.swing.JTextField();
        tf_nama = new javax.swing.JTextField();
        tf_ISBN = new javax.swing.JTextField();
        tf_judul = new javax.swing.JTextField();
        tf_tanggalpin = new javax.swing.JTextField();
        tf_tanggalkem = new javax.swing.JTextField();
        tf_nohp = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_kodepinjam1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();
        tumbal_stok = new javax.swing.JLabel();
        tumbal_update_stok = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tf_NIS.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 12)); // NOI18N
        tf_NIS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        tf_NIS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_NISKeyReleased(evt);
            }
        });
        getContentPane().add(tf_NIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 150, 300, 40));

        tf_nama.setEditable(false);
        tf_nama.setBackground(new java.awt.Color(255, 255, 255));
        tf_nama.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 12)); // NOI18N
        tf_nama.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        getContentPane().add(tf_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 200, 300, 40));

        tf_ISBN.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 12)); // NOI18N
        tf_ISBN.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        tf_ISBN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_ISBNKeyReleased(evt);
            }
        });
        getContentPane().add(tf_ISBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, 300, 40));

        tf_judul.setEditable(false);
        tf_judul.setBackground(new java.awt.Color(255, 255, 255));
        tf_judul.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 12)); // NOI18N
        tf_judul.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        getContentPane().add(tf_judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 350, 300, 40));

        tf_tanggalpin.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 12)); // NOI18N
        tf_tanggalpin.setText("Tanggal/Bulan/Tahun");
        tf_tanggalpin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        tf_tanggalpin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_tanggalpinMouseClicked(evt);
            }
        });
        getContentPane().add(tf_tanggalpin, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 400, 300, 40));

        tf_tanggalkem.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 12)); // NOI18N
        tf_tanggalkem.setText("Tanggal/Bulan/Tahun");
        tf_tanggalkem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        tf_tanggalkem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_tanggalkemMouseClicked(evt);
            }
        });
        getContentPane().add(tf_tanggalkem, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 450, 300, 40));

        tf_nohp.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 12)); // NOI18N
        tf_nohp.setText("08xx-xxxx-xxxx");
        tf_nohp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        tf_nohp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_nohpMouseClicked(evt);
            }
        });
        getContentPane().add(tf_nohp, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 500, 300, 40));

        jPanel2.setBackground(new java.awt.Color(0, 255, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 20)); // NOI18N
        jLabel1.setText("          SIMPAN");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 585, 190, 50));

        jLabel9.setFont(new java.awt.Font("Arial Black", 3, 22)); // NOI18N
        jLabel9.setText("PERPUSTAKAAN");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(392, 0, 230, 20));

        jLabel10.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 20)); // NOI18N
        jLabel10.setText("No handphone Admin");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 500, 280, 40));

        jLabel11.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 35)); // NOI18N
        jLabel11.setText("PEMINJAMAN BUKU");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 75, -1, -1));

        jLabel12.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 20)); // NOI18N
        jLabel12.setText("NIS");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 300, 40));

        jLabel13.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 20)); // NOI18N
        jLabel13.setText("Nama peminjam");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 250, 40));

        jLabel14.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 20)); // NOI18N
        jLabel14.setText("Kode Buku (ISBN)");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 250, 40));

        jLabel15.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 20)); // NOI18N
        jLabel15.setText("Judul buku yang di pinjam");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 320, 40));

        jLabel16.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 20)); // NOI18N
        jLabel16.setText("Hari dan tanggal peminjaman");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 330, 40));

        jLabel17.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 20)); // NOI18N
        jLabel17.setText("Hari dan tanggal pengembalian");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 450, 370, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arrow left.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 60, 50));

        tf_kodepinjam1.setEditable(false);
        tf_kodepinjam1.setBackground(new java.awt.Color(255, 255, 255));
        tf_kodepinjam1.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 12)); // NOI18N
        tf_kodepinjam1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        getContentPane().add(tf_kodepinjam1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 300, 40));

        jLabel18.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 20)); // NOI18N
        jLabel18.setText("Kode pinjam");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 250, 40));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Peminjaman (1).png"))); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 680));

        tumbal_stok.setText("jLabel2");
        getContentPane().add(tumbal_stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, -1));

        tumbal_update_stok.setText("jLabel2");
        getContentPane().add(tumbal_update_stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        if(tf_nohp.getText().equals("")){
                JOptionPane.showMessageDialog(null,"No HP Tidak Boleh Kosong / No HP Kurang Lengkap"); 
            }else if (tf_NIS.getText().equals("")){
                JOptionPane.showMessageDialog(null,"NIS Tidak Boleh Kosong / Mohon Periksa Kembali NIS yang Anda Masukan"); 
            }else if (tf_nama.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Kolom Tidak Boleh Kosong, Mohon di isi dengan Benar");
            }else if (tf_kodepinjam1.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Kolom ini Tidak Boleh Kososng, Mohon di isi dengan Benar");
            }else if(tf_ISBN.getText().equals("")){
                JOptionPane.showMessageDialog(null,"ISBN Tidak Sesuai, Mohon Periksa Kembali");
            } else if (tf_judul.getText().equals("")){
                JOptionPane.showMessageDialog(null,"Kolom ini Tidak Boleh Kososng, Mohon di isi dengan Bena");
            } else {
        
        
        String sql = "insert into peminjaman (NIS,nama,kodepinjam,ISBN,judul,tanggalpin,tanggalkem,nohp)values (?,?,?,?,?,?,?,?);";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, tf_NIS.getText());
            stat.setString(2, tf_nama.getText());
            stat.setString(3, tf_kodepinjam1.getText());
            stat.setString(4, tf_ISBN.getText());
            stat.setString(5, tf_judul.getText());
            stat.setString(6, tf_tanggalpin.getText());
            stat.setString(7, tf_tanggalkem.getText());
            stat.setString(8, tf_nohp.getText());
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil di simpan");
            Update_Stok();
            auto_number();
            kosong();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Gagal di simpan " + e);
        }
            }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void tf_tanggalpinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_tanggalpinMouseClicked
        // TODO add your handling code here:
        tf_tanggalpin.setText("");
       
    }//GEN-LAST:event_tf_tanggalpinMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void tf_tanggalkemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_tanggalkemMouseClicked
        // TODO add your handling code here:
         tf_tanggalkem.setText("");
    }//GEN-LAST:event_tf_tanggalkemMouseClicked

    private void tf_nohpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_nohpMouseClicked
        // TODO add your handling code here:
         tf_nohp.setText("");
    }//GEN-LAST:event_tf_nohpMouseClicked

    private void tf_ISBNKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_ISBNKeyReleased
        // TODO add your handling code here:
        dataAdmin();
        stok();
    }//GEN-LAST:event_tf_ISBNKeyReleased

    private void tf_NISKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_NISKeyReleased
        // TODO add your handling code here:
        nama();
    }//GEN-LAST:event_tf_NISKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Peminjaman1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Peminjaman1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Peminjaman1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Peminjaman1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Peminjaman1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tf_ISBN;
    private javax.swing.JTextField tf_NIS;
    private javax.swing.JTextField tf_judul;
    private javax.swing.JTextField tf_kodepinjam1;
    private javax.swing.JTextField tf_nama;
    private javax.swing.JTextField tf_nohp;
    private javax.swing.JTextField tf_tanggalkem;
    private javax.swing.JTextField tf_tanggalpin;
    public static javax.swing.JLabel tumbal_stok;
    private javax.swing.JLabel tumbal_update_stok;
    // End of variables declaration//GEN-END:variables
}
