/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Admin;

import static com.Admin.Peminjaman1.tumbal_stok;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import koneksi.New_ConnectDB;

/**
 *
 * @author hp
 */
public class Pengembalian_Buku_Admin extends javax.swing.JFrame {
    private Connection conn = new New_ConnectDB().connect();
    

    /**
     * Creates new form NewJFrame
     */
    public Pengembalian_Buku_Admin() {
        initComponents();
        setLocationRelativeTo(this);
    }
    
    protected void stok() {
         String sql = "select * from data_buku where ISBN = '"+ tf_ISBN.getText() + "' ";//asc paling kecil
         
         try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String sjudul = hasil.getString("jumlah");
                tumbal_stok.setText(sjudul);
                //tabmode.addRow(data);

            }
        } catch (Exception e) {
        }
         
    }
    protected void Update_Stok() {
        int a = Integer.parseInt(tumbal_stok.getText());
        int stotal = a + 1;
        tumbal_update_stok.setText(""+stotal);
        try {
            String sql = "update data_buku set jumlah='"+tumbal_update_stok.getText()+"' where ISBN='"+tf_ISBN.getText()+"'";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.executeUpdate();
        }catch (SQLException e) {
            JOptionPane.showMessageDialog(null,
                    "Hubungi Administrator +62 8778-8298-067" +e);
        }
    }

    
    
    protected void kosong(){
        tf_kodepin.setText("");
        tf_NIS.setText("");
        tf_nama1.setText("");
        tf_ISBN.setText("");
        tf_judul.setText("");
        tf_nohp.setText("");
        tf_tanggalpin.setText("");
        tf_tanggalkem.setText("");
        tf_denda.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf_kodepin = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        tf_NIS = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        tf_judul = new javax.swing.JTextField();
        tf_nohp = new javax.swing.JTextField();
        tf_tanggalpin = new javax.swing.JTextField();
        tf_tanggalkem = new javax.swing.JTextField();
        tf_denda = new javax.swing.JTextField();
        tf_nama1 = new javax.swing.JTextField();
        tf_ISBN = new javax.swing.JTextField();
        Backgroud = new javax.swing.JLabel();
        tumbal_stok = new javax.swing.JLabel();
        tumbal_update_stok = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tf_kodepin.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 12)); // NOI18N
        tf_kodepin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_kodepinActionPerformed(evt);
            }
        });
        tf_kodepin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_kodepinKeyReleased(evt);
            }
        });
        getContentPane().add(tf_kodepin, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 300, 30));

        jPanel2.setBackground(new java.awt.Color(0, 255, 0));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 20)); // NOI18N
        jLabel12.setText("       SIMPAN");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 556, 170, 50));

        tf_NIS.setEditable(false);
        tf_NIS.setBackground(new java.awt.Color(255, 255, 255));
        tf_NIS.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 12)); // NOI18N
        getContentPane().add(tf_NIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 300, 30));

        jLabel1.setFont(new java.awt.Font("Arial Black", 3, 22)); // NOI18N
        jLabel1.setText("PERPUSTAKAAN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 230, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arrow left.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 60, 50));

        jLabel17.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 35)); // NOI18N
        jLabel17.setText("PENGEMBALIAN BUKU");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, -1, -1));

        jLabel18.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 20)); // NOI18N
        jLabel18.setText("Denda");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 520, 220, 30));

        jLabel19.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 20)); // NOI18N
        jLabel19.setText("Kode pinjam");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 220, 30));

        jLabel20.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 20)); // NOI18N
        jLabel20.setText("NIS");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 220, 30));

        jLabel21.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 20)); // NOI18N
        jLabel21.setText("Nama peminjam");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 220, 30));

        jLabel22.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 20)); // NOI18N
        jLabel22.setText("Kode buku (ISBN)");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 220, 30));

        jLabel23.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 20)); // NOI18N
        jLabel23.setText("Judul buku");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 220, 30));

        jLabel24.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 20)); // NOI18N
        jLabel24.setText("No handphone");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 220, 30));

        jLabel25.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 20)); // NOI18N
        jLabel25.setText("Tanggal peminjaman");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, -1, 30));

        jLabel26.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 20)); // NOI18N
        jLabel26.setText("Tanggal pengembalian");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 480, -1, 30));

        tf_judul.setEditable(false);
        tf_judul.setBackground(new java.awt.Color(255, 255, 255));
        tf_judul.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 12)); // NOI18N
        getContentPane().add(tf_judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, 300, 30));

        tf_nohp.setEditable(false);
        tf_nohp.setBackground(new java.awt.Color(255, 255, 255));
        tf_nohp.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 12)); // NOI18N
        getContentPane().add(tf_nohp, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, 300, 30));

        tf_tanggalpin.setEditable(false);
        tf_tanggalpin.setBackground(new java.awt.Color(255, 255, 255));
        tf_tanggalpin.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 12)); // NOI18N
        getContentPane().add(tf_tanggalpin, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, 300, 30));

        tf_tanggalkem.setEditable(false);
        tf_tanggalkem.setBackground(new java.awt.Color(255, 255, 255));
        tf_tanggalkem.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 12)); // NOI18N
        getContentPane().add(tf_tanggalkem, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 480, 300, 30));

        tf_denda.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 12)); // NOI18N
        getContentPane().add(tf_denda, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 520, 300, 30));

        tf_nama1.setEditable(false);
        tf_nama1.setBackground(new java.awt.Color(255, 255, 255));
        tf_nama1.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 12)); // NOI18N
        getContentPane().add(tf_nama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 300, 30));

        tf_ISBN.setEditable(false);
        tf_ISBN.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 12)); // NOI18N
        tf_ISBN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_ISBNKeyReleased(evt);
            }
        });
        getContentPane().add(tf_ISBN, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 300, 30));

        Backgroud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/merapikan.png"))); // NOI18N
        getContentPane().add(Backgroud, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 680));

        tumbal_stok.setText("jLabel2");
        getContentPane().add(tumbal_stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, -1));

        tumbal_update_stok.setText("jLabel2");
        getContentPane().add(tumbal_update_stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        String sql = "insert into pengembalian (kodepinjam,NIS,nama,ISBN,judul,nohp,tanggalpin,tanggalkem,denda)values (?,?,?,?,?,?,?,?,?);";
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, tf_kodepin.getText());
            stat.setString(2, tf_NIS.getText());
            stat.setString(3, tf_nama1.getText());
            stat.setString(4, tf_ISBN.getText());
            stat.setString(5, tf_judul.getText());
            stat.setString(6, tf_nohp.getText());
            stat.setString(7, tf_tanggalpin.getText());
            stat.setString(8, tf_tanggalkem.getText());
            stat.setString(9, tf_denda.getText());
            stat.executeUpdate();
            Update_Stok();
            JOptionPane.showMessageDialog(null, "Data Berhasil di Ubah");
            kosong();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Gagal di Ubah " + e);
        }
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseClicked

    private void tf_kodepinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_kodepinActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "select NIS, nama,ISBN,judul, nohp, tanggalpin, tanggalkem from peminjaman where kodepinjam = '" + tf_kodepin.getText()+"'";
            PreparedStatement stat = conn.prepareStatement(sql);
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String nis = hasil.getString("NIS");
                String nama = hasil.getString("nama");
                String isbn = hasil.getString("ISBN");
                String judul = hasil.getString("judul");
                String nohp = hasil.getString("nohp");
                String tanggalpin = hasil.getString("tanggalpin");
                String tanggalkem = hasil.getString("tanggalkem");
                tf_NIS.setText(nis);
                tf_nama1.setText(nama);
                tf_ISBN.setText(isbn);
                tf_judul.setText(judul);
                tf_nohp.setText(nohp);
                tf_tanggalpin.setText(tanggalpin);
                tf_tanggalkem.setText(tanggalkem);
                stok();
                
            }
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_tf_kodepinActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        dispose();
        //jLabel7.setText(""+jLabel6);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void tf_kodepinKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_kodepinKeyReleased
        // TODO add your handling code here:
        try {
            String sql = "select NIS, nama,ISBN,judul, nohp, tanggalpin, tanggalkem from peminjaman where kodepinjam = '" + tf_kodepin.getText()+"'";
            PreparedStatement stat = conn.prepareStatement(sql);
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()) {
                String nis = hasil.getString("NIS");
                String nama = hasil.getString("nama");
                String isbn = hasil.getString("ISBN");
                String judul = hasil.getString("judul");
                String nohp = hasil.getString("nohp");
                String tanggalpin = hasil.getString("tanggalpin");
                String tanggalkem = hasil.getString("tanggalkem");
                tf_NIS.setText(nis);
                tf_nama1.setText(nama);
                tf_ISBN.setText(isbn);
                tf_judul.setText(judul);
                tf_nohp.setText(nohp);
                tf_tanggalpin.setText(tanggalpin);
                tf_tanggalkem.setText(tanggalkem);
                stok();
                
            }
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_tf_kodepinKeyReleased

    private void tf_ISBNKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_ISBNKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tf_ISBNKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pengembalian_Buku_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pengembalian_Buku_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pengembalian_Buku_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pengembalian_Buku_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pengembalian_Buku_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Backgroud;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tf_ISBN;
    private javax.swing.JTextField tf_NIS;
    private javax.swing.JTextField tf_denda;
    private javax.swing.JTextField tf_judul;
    private javax.swing.JTextField tf_kodepin;
    private javax.swing.JTextField tf_nama1;
    private javax.swing.JTextField tf_nohp;
    private javax.swing.JTextField tf_tanggalkem;
    private javax.swing.JTextField tf_tanggalpin;
    public static javax.swing.JLabel tumbal_stok;
    private javax.swing.JLabel tumbal_update_stok;
    // End of variables declaration//GEN-END:variables
}
