/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Admin;

/**
 *
 * @author Hard JFS
 */
public class PopupTrendingADMIN3 extends javax.swing.JFrame {

    /**
     * Creates new form Popuptrending3
     */
    public PopupTrendingADMIN3() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        vir_judul3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        vir_stok3 = new javax.swing.JLabel();
        vir_penulis3 = new javax.swing.JLabel();
        vir_penerbit3 = new javax.swing.JLabel();
        vir_tahun3 = new javax.swing.JLabel();
        Penulis3 = new javax.swing.JLabel();
        Penerbit3 = new javax.swing.JLabel();
        vir_isbn3 = new javax.swing.JLabel();
        Isbn3 = new javax.swing.JLabel();
        Tahun_Terbit3 = new javax.swing.JLabel();
        popup = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 50));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arrow left.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/open-book(2).png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 45, 80, 60));

        vir_judul3.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 18)); // NOI18N
        vir_judul3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vir_judul3.setText("Judul Buku");
        getContentPane().add(vir_judul3, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 110, 330, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bintang 3 (1).png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 140, 130, -1));

        jLabel3.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 14)); // NOI18N
        jLabel3.setText("Rating");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 143, -1, 20));

        jLabel6.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 14)); // NOI18N
        jLabel6.setText("Stok Buku");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 172, -1, 30));

        vir_stok3.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 14)); // NOI18N
        vir_stok3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vir_stok3.setText("00000");
        getContentPane().add(vir_stok3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 172, -1, 30));

        vir_penulis3.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 18)); // NOI18N
        vir_penulis3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        vir_penulis3.setText("?");
        getContentPane().add(vir_penulis3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 300, 30));

        vir_penerbit3.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 18)); // NOI18N
        vir_penerbit3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        vir_penerbit3.setText("?");
        getContentPane().add(vir_penerbit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 300, 30));

        vir_tahun3.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 18)); // NOI18N
        vir_tahun3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        vir_tahun3.setText("?");
        getContentPane().add(vir_tahun3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 300, 30));

        Penulis3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Penulis3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Penulis3.setText("Penulis :");
        getContentPane().add(Penulis3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 225, -1, -1));

        Penerbit3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Penerbit3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Penerbit3.setText("Penerbit :");
        getContentPane().add(Penerbit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        vir_isbn3.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 18)); // NOI18N
        vir_isbn3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        vir_isbn3.setText("?");
        getContentPane().add(vir_isbn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 300, 30));

        Isbn3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Isbn3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Isbn3.setText("ISBN :");
        getContentPane().add(Isbn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        Tahun_Terbit3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Tahun_Terbit3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tahun_Terbit3.setText("Tahun Terbit :");
        getContentPane().add(Tahun_Terbit3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        popup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/popuptrenAD.png"))); // NOI18N
        popup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                popupMouseExited(evt);
            }
        });
        getContentPane().add(popup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    private void popupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_popupMouseExited
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_popupMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PopupTrendingADMIN3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Isbn3;
    private javax.swing.JLabel Penerbit3;
    private javax.swing.JLabel Penulis3;
    private javax.swing.JLabel Tahun_Terbit3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel popup;
    public static javax.swing.JLabel vir_isbn3;
    public static javax.swing.JLabel vir_judul3;
    public static javax.swing.JLabel vir_penerbit3;
    public static javax.swing.JLabel vir_penulis3;
    public static javax.swing.JLabel vir_stok3;
    public static javax.swing.JLabel vir_tahun3;
    // End of variables declaration//GEN-END:variables
}
