/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.Admin;

/**
 *
 * @author Hard JFS
 */
public class PopupTrendingADMIN1 extends javax.swing.JFrame {

    /**
     * Creates new form PopupTrending1
     */
    public PopupTrendingADMIN1() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        vir_judul = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        vir_stok = new javax.swing.JLabel();
        vir_penulis = new javax.swing.JLabel();
        vir_penerbit = new javax.swing.JLabel();
        vir_tahun = new javax.swing.JLabel();
        vir_isbn = new javax.swing.JLabel();
        Isbn1 = new javax.swing.JLabel();
        Penerbit1 = new javax.swing.JLabel();
        Penulis1 = new javax.swing.JLabel();
        Tahun_Terbit1 = new javax.swing.JLabel();
        BgPopup = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 50));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arrow left.png"))); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/open-book.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 45, 80, 60));

        vir_judul.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 18)); // NOI18N
        vir_judul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vir_judul.setText("Judul Buku");
        getContentPane().add(vir_judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 110, 330, -1));

        jLabel3.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 14)); // NOI18N
        jLabel3.setText("Rating");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 143, -1, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bintang 1.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 140, 130, -1));

        jLabel6.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 14)); // NOI18N
        jLabel6.setText("Stok Buku ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 172, -1, 30));

        vir_stok.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 14)); // NOI18N
        vir_stok.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vir_stok.setText("00000");
        getContentPane().add(vir_stok, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 174, -1, 30));

        vir_penulis.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 18)); // NOI18N
        vir_penulis.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        vir_penulis.setText("?");
        getContentPane().add(vir_penulis, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 300, 30));

        vir_penerbit.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 18)); // NOI18N
        vir_penerbit.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        vir_penerbit.setText("?");
        getContentPane().add(vir_penerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 300, 30));

        vir_tahun.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 18)); // NOI18N
        vir_tahun.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        vir_tahun.setText("?");
        getContentPane().add(vir_tahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 300, 30));

        vir_isbn.setFont(new java.awt.Font("Open Sans ExtraBold", 1, 18)); // NOI18N
        vir_isbn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        vir_isbn.setText("?");
        getContentPane().add(vir_isbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 300, 30));

        Isbn1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Isbn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Isbn1.setText("ISBN :");
        getContentPane().add(Isbn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        Penerbit1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Penerbit1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Penerbit1.setText("Penerbit :");
        getContentPane().add(Penerbit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        Penulis1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Penulis1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Penulis1.setText("Penulis :");
        getContentPane().add(Penulis1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 225, -1, -1));

        Tahun_Terbit1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Tahun_Terbit1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tahun_Terbit1.setText("Tahun Terbit :");
        getContentPane().add(Tahun_Terbit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        BgPopup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/popuptrenAD.png"))); // NOI18N
        BgPopup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BgPopupMouseExited(evt);
            }
        });
        getContentPane().add(BgPopup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        dispose();
        new Home_Admin().setVisible(true);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void BgPopupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BgPopupMouseExited
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BgPopupMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PopupTrendingADMIN1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PopupTrendingADMIN1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PopupTrendingADMIN1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PopupTrendingADMIN1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PopupTrendingADMIN1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BgPopup;
    private javax.swing.JLabel Isbn1;
    private javax.swing.JLabel Penerbit1;
    private javax.swing.JLabel Penulis1;
    private javax.swing.JLabel Tahun_Terbit1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel vir_isbn;
    public static javax.swing.JLabel vir_judul;
    public static javax.swing.JLabel vir_penerbit;
    public static javax.swing.JLabel vir_penulis;
    public static javax.swing.JLabel vir_stok;
    public static javax.swing.JLabel vir_tahun;
    // End of variables declaration//GEN-END:variables
}
